USE [master]
GO

/****** Object:  Database [RavenReplication]    Script Date: 11/27/2012 20:10:49 ******/
CREATE DATABASE [RavenReplication] ON  PRIMARY 
( NAME = N'RavenReplication', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\RavenReplication.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RavenReplication_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\RavenReplication_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [RavenReplication] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RavenReplication].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RavenReplication] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RavenReplication] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RavenReplication] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RavenReplication] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RavenReplication] SET ARITHABORT OFF 
GO

ALTER DATABASE [RavenReplication] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RavenReplication] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [RavenReplication] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RavenReplication] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RavenReplication] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RavenReplication] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RavenReplication] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RavenReplication] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RavenReplication] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RavenReplication] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RavenReplication] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RavenReplication] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RavenReplication] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RavenReplication] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RavenReplication] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RavenReplication] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RavenReplication] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RavenReplication] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RavenReplication] SET  READ_WRITE 
GO

ALTER DATABASE [RavenReplication] SET RECOVERY FULL 
GO

ALTER DATABASE [RavenReplication] SET  MULTI_USER 
GO

ALTER DATABASE [RavenReplication] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RavenReplication] SET DB_CHAINING OFF 
GO


